import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#2563eb",
        "on-primary": "#ffffff",
        "primary-container": "#dbeafe",
        "on-primary-container": "#1d4ed8",
        "primary-fixed": "#dbeafe",
        "primary-fixed-dim": "#93c5fd",
        "on-primary-fixed": "#1d4ed8",
        "on-primary-fixed-variant": "#1e40af",
        "secondary": "#10b981",
        "on-secondary": "#ffffff",
        "secondary-container": "#d1fae5",
        "on-secondary-container": "#047857",
        "secondary-fixed": "#d1fae5",
        "secondary-fixed-dim": "#6ee7b7",
        "on-secondary-fixed": "#064e3b",
        "on-secondary-fixed-variant": "#047857",
        "tertiary": "#1f2937",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#f1f5f9",
        "on-tertiary-container": "#1f2937",
        "tertiary-fixed": "#e2e8f0",
        "tertiary-fixed-dim": "#cbd5e1",
        "on-tertiary-fixed": "#0f172a",
        "on-tertiary-fixed-variant": "#334155",
        "surface": "#f8fafc",
        "surface-dim": "#e2e8f0",
        "surface-bright": "#f8fafc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8fafc",
        "surface-container": "#f1f5f9",
        "surface-container-high": "#e2e8f0",
        "surface-container-highest": "#cbd5e1",
        "on-surface": "#1f2937",
        "on-surface-variant": "#475569",
        "outline": "#94a3b8",
        "outline-variant": "#cbd5e1",
        "background": "#f8fafc",
        "foreground": "#1f2937",
        "on-background": "#1f2937",
        "inverse-surface": "#0f172a",
        "inverse-on-surface": "#f8fafc",
        "inverse-primary": "#93c5fd",
        "surface-tint": "#2563eb",
        "surface-variant": "#e2e8f0",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        "h1": ["Manrope", "sans-serif"],
        "h2": ["Manrope", "sans-serif"],
        "h3": ["Manrope", "sans-serif"],
        "body-lg": ["Lexend", "sans-serif"],
        "body-md": ["Lexend", "sans-serif"],
        "body-sm": ["Lexend", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
      },
      fontSize: {
        "h1": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h2": ["36px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h3": ["24px", { lineHeight: "1.4", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "300" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "300" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "300" }],
        "label-bold": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "button": ["16px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "500" }],
      },
      spacing: {
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "gutter": "24px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "container-max": "1280px",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}

export default config
