import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#021064",
        "on-primary": "#ffffff",
        "primary-container": "#1e2a78",
        "on-primary-container": "#8a95e9",
        "primary-fixed": "#dfe0ff",
        "primary-fixed-dim": "#bcc3ff",
        "on-primary-fixed": "#000d60",
        "on-primary-fixed-variant": "#343f8d",
        "secondary": "#006a62",
        "on-secondary": "#ffffff",
        "secondary-container": "#70f8e8",
        "on-secondary-container": "#007168",
        "secondary-fixed": "#70f8e8",
        "secondary-fixed-dim": "#4fdbcc",
        "on-secondary-fixed": "#00201d",
        "on-secondary-fixed-variant": "#005049",
        "tertiary": "#391100",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#5b2000",
        "on-tertiary-container": "#dc845b",
        "tertiary-fixed": "#ffdbcc",
        "tertiary-fixed-dim": "#ffb595",
        "on-tertiary-fixed": "#351000",
        "on-tertiary-fixed-variant": "#753311",
        "surface": "#fbf8ff",
        "surface-dim": "#dbd9e0",
        "surface-bright": "#fbf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f2fa",
        "surface-container": "#efedf4",
        "surface-container-high": "#e9e7ee",
        "surface-container-highest": "#e4e1e9",
        "on-surface": "#1b1b20",
        "on-surface-variant": "#454651",
        "outline": "#767682",
        "outline-variant": "#c6c5d3",
        "background": "#fbf8ff",
        "foreground": "#1b1b20",
        "on-background": "#1b1b20",
        "inverse-surface": "#303036",
        "inverse-on-surface": "#f2eff7",
        "inverse-primary": "#bcc3ff",
        "surface-tint": "#4c58a6",
        "surface-variant": "#e4e1e9",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        "h1": ["Manrope", "sans-serif"],
        "h2": ["Manrope", "sans-serif"],
        "h3": ["Manrope", "sans-serif"],
        "body-lg": ["Lexend", "sans-serif"],
        "body-md": ["Lexend", "sans-serif"],
        "body-sm": ["Lexend", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
      },
      fontSize: {
        "h1": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h2": ["36px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h3": ["24px", { lineHeight: "1.4", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "300" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "300" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "300" }],
        "label-bold": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "button": ["16px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "500" }],
      },
      spacing: {
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "gutter": "24px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "container-max": "1280px",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}

export default config
