export type LegalSection = {
  title: string
  paragraphs: string[]
}

export const refundPolicySections: LegalSection[] = [
  {
    title: 'Refund Policy',
    paragraphs: [
      'The EduMindWell renders services including but not limited to counseling, assessment tests etc, which act as a bonafide guide to the user and the services are rendered as soon as availed, therefore there is no provision for refund of fee paid by the User/s. The user/s is therefore deemed to have understood and accepted that once the fee is paid to the EduMindWell as per the services availed, there shall be no refund of the said Fee.',
    ],
  },
]

export const termsAndConditionsSections: LegalSection[] = [
  {
    title: 'Introduction',
    paragraphs: [
      'This document is an electronic record in terms of Information Technology Act, 2000 and Rules made there under as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures.',
      'This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and user agreement of access or usage of a website. Here website means www.EduMindWell.com.',
      'www.EduMindWell.com, is a technology enabled multi dimensional career assessment website that helps the users in career planning in the best of their interests. Before using our services/products you should go through the present Agreement, hereinafter referred to as EDUMINDWELL, and agree to the terms and conditions of the EDUMINDWELL. The User of the site shall be deemed to have read the terms of the EDUMINDWELL and duly accepted them before browsing through the website.',
      'These terms may be changed or updated from time to time solely at our discretion. By using our site you will be bound by the terms and conditions as mentioned in the EDUMINDWELL. You are required to and responsible for regularly reviewing the EDUMINDWELL to keep yourself updated with the changes or amendments to the EDUMINDWELL as made by us from time to time. If you continue to access the website subsequent to such changes to EDUMINDWELL, you will be deemed to have accepted and agreed to the said changes.',
    ],
  },
  {
    title: 'Reference of Terms Used in EDUMINDWELL',
    paragraphs: [
      'The term EduMindWell is used through this entire EDUMINDWELL to refer to the Website, its owner, directors, employees, and individuals/entities associated with the Owner.',
      'Owner refers to EduMindWell.',
      'The term USER or YOU or YOUR is used through this entire EDUMINDWELL to refer to any person who accesses the website or who is/are registered at the website for various services provided by it. User would include individual/legal entity/society/group of people etc. or as the case may be.',
      'The term OUR WEBSITE or WEBSITE is used through this entire EDUMINDWELL to refer to the Website www.EduMindWell.com.',
      'The term OUR PRODUCTS/SERVICES is used through this entire EDUMINDWELL to refer to the products/services offered at the Website or its associated entities, not including the advertisements that may be displayed on the Website.',
      'The term APPROPRIATE GOVERNMENT is used through this entire EDUMINDWELL as referring to Central/State Government or Local authorities as the case may be.',
      'The terms and conditions herein shall apply equally to both the singular and plural form of the terms. Whenever the context may require, any pronoun shall include both the corresponding masculine and feminine form. The terms as defined herein shall also read as such in the Privacy Policy as well as the Disclaimer of the Website.',
    ],
  },
  {
    title: 'Eligibility',
    paragraphs: [
      'Use of the Website is available to all the persons/entities/companies/partnership firms etc., as the case may be. However, any registration on the website shall be by the person who is capable of entering into valid contract as per the Indian Contract Act, 1872.',
      'Persons who are incompetent to contract within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website, except under the legal/constructive guardianship of such persons capable of entering into contract on behalf of such minor user/s.',
      'While registering with the Website, you represent that the information filled by you is correct and that you are duly authorized to accept this agreement and you have the authority to bind yourself/your business entity to this agreement. You further confirm that you shall use/browse the Website in terms of the EDUMINDWELL.',
      'EduMindWell reserves the right to terminate your registration and refuse to provide you with access to the Website if it is brought to our notice or if it is discovered that you are using the site in violation of the EDUMINDWELL or at its sole discretion without any reason thereof.',
    ],
  },
  {
    title: 'Registration Obligation',
    paragraphs: [
      'You are responsible for maintaining the confidentiality of your User ID and Password. You are responsible for all the activities that occur under your User ID and Password.',
      'You agree to provide true, accurate, current and complete information about yourself as prompted by EduMindWell registration form, maintain and promptly update the Registration Data to keep it true, accurate, current, and complete at all times.',
      'You must immediately notify us of any unauthorized use of your password or account or any other breach of security, and ensure that you exit from your account at the end of each session.',
      'If you provide any information that is untrue, inaccurate, not current, or incomplete or EduMindWell has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with this Agreement, EduMindWell has the right to indefinitely suspend or terminate or block access of your registration with the website.',
      'EduMindWell shall not be liable for any loss or damage arising from your failure to comply with this Clause.',
    ],
  },
  {
    title: 'Electronic Registration and Communication',
    paragraphs: [
      'When you use the Website or send emails or other data, information or communication to EduMindWell, you agree and understand that you are communicating with EduMindWell through electronic records. You consent to receive communications from us electronically. We will communicate with you by email or by posting notices on the Website or through any other EduMindWell services.',
    ],
  },
  {
    title: 'Description of Services',
    paragraphs: [
      'EduMindWell is a technology enabled eco-system for career planning and development for students. We leverage technology, research, machine learning and algorithms to minimize the human bias in career decision making process. EduMindWell offers a unique way of career guidance, counseling and mentoring and is not limited to psychometric assessments, career counselling and guidance, interactive career focused activities and career progression or tracking mechanisms etc., as may be provided time to time for help and guidance of user/s.',
      'By entering into the present agreement, you accept that you are using the services rendered at EduMindWell at your sole discretion without any undue influence of the EduMindWell and at your sole responsibility, under supervision of guardian in case of minors.',
      'You further agree to ensure that you will avail the services with due care and due diligence and as per the terms and conditions of the EDUMINDWELL and the respective service you are availing.',
    ],
  },
  {
    title: 'Fees and Taxes',
    paragraphs: [
      'EduMindWell shall charge the fee for the services provided as per the structure provided on the website. By using the services which are subject to payment, as mentioned therein, you accept to pay for the same before using the services.',
      'You further undertake not to raise any dispute qua the fee charged for the services in any manner whatsoever as you have agreed to the same out of free will and without any undue influence.',
      'You further undertake that you have read the Terms and Conditions of the Payment that are prompted when you move towards payment of the paid services and have accepted the same before making the payment.',
      'EduMindWell uses third party payments providers to receive payments from user. EduMindWell is not responsible for delays or erroneous transactions execution or cancellation of orders due to payment issues. EduMindWell takes utmost care to work with third party payment providers, but does not control their systems, processes, technology and work flows, hence cannot be held responsible for any fault at the end of payment providers.',
      'The fee to be charged by EduMindWell from users shall be decided solely by EduMindWell and the user/s shall have no right/say to interfere in the same.',
      'You agree to bear all applicable taxes, charges cess etc. levied on the services being rendered to you as notified by the Central/State Govt. time to time, unless already included in the price offered.',
    ],
  },
  {
    title: 'Term and Termination of the Contract',
    paragraphs: [
      'There shall be no Contract between the EduMindWell and the user/s until the services are availed by user/s against consideration. The access to the free portion of the website is only for welfare of the user and does not give rise to any Contract between the user/s and the EduMindWell in any manner.',
      'The Contract against consideration for the services shall be strictly in terms of the services availed and shall end as soon as the services are rendered.',
      'EduMindWell is entitled to terminate the contract at all times and with immediate effect, by disabling your use of the Website and the Service, if you violate or breach any term of this EDUMINDWELL, if in the opinion of EduMindWell you misuse the Website or Service, or at the sole discretion of the EduMindWell for which EduMindWell is under no obligation to assign any reason.',
      'EduMindWell is not obliged to give prior notice of the termination of contract.',
    ],
  },
  {
    title: 'Intellectual Property Ownership',
    paragraphs: [
      'EduMindWell alone, and its licensors where applicable, shall own all right, title and interest, including all intellectual property rights, in and to the Website and Service and any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by you or any other party relating to the Website or the Service.',
      'You may not use, copy, adapt, modify, create derivative works from, distribute, license, sell, transfer, publicly display, publicly perform, reproduce, transmit, stream, broadcast or otherwise exploit the Website, Service or Collective Content, except as expressly permitted in this EduMindWell. You may not use any Collective Content without first obtaining the written consent of EduMindWell.',
      'No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by EduMindWell or its licensors, except for the licenses and rights expressly granted in this Agreement.',
      'This EDUMINDWELL does not constitute a sale and does not convey to you any rights of ownership in or related to the Website, or any intellectual property rights owned by EduMindWell. EduMindWell name, logo, and the product names associated with the Website and the Service are trademarks of Owner, its affiliated companies or third parties, and no right or license is granted to use them.',
    ],
  },
  {
    title: 'Website License',
    paragraphs: [
      'Subject to your compliance with these EDUMINDWELL, EduMindWell grants you a limited non-exclusive, non-transferable license for the use of the Website.',
      'You shall not license, sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Service or Website in any way; modify or make derivative works based upon the Service or Website; create internet links to the Service or frame or mirror any Website or any other server or wireless or Internet-based device.',
      'You shall not reverse engineer or access the Website in order to design or build a competitive product or service, design or build a product using similar ideas, features, functions, or graphics of the Service or Website, or copy any ideas, features, functions or graphics of the Service or Website.',
      'You shall not launch an automated program or script, including web spiders, web crawlers, web robots, bots, viruses or worms or any program which may make multiple server requests per second, or unduly burdens or hinders the operation and/or performance of the Website.',
      'You shall not send spam or otherwise duplicative or unsolicited messages in violation of applicable laws, send or store infringing, obscene, threatening, libelous, or otherwise unlawful or tortious material, send or store material containing software viruses, worms, Trojan horses or other harmful code, interfere with or disrupt the integrity or performance of the Website, or attempt to gain unauthorized access to the website.',
      'You will not authorize others to use your account, assign or otherwise transfer your account, use an account subject to rights of another person without authorization, use the Service or website for unlawful purposes, and will comply with all applicable law from your home nation, country, state and/or city in which you are present while using the Website or Service.',
      'EduMindWell will have the right to investigate and prosecute violations of any of the above to the fullest extent of the law. EduMindWell may involve and cooperate with law enforcement authorities in prosecuting users who violate these User Terms.',
      'EduMindWell reserves the right, at any time and without prior notice, to remove or disable access to any Collective Content that EduMindWell, at its sole discretion, considers to be in violation of these User Terms or otherwise harmful to the Website, the Service or Website.',
    ],
  },
  {
    title: 'Conditions for Use of Website',
    paragraphs: [
      'In accordance with the Information Technology (Intermediaries guidelines) Rules 2011 and further guidelines as may be issued by the appropriate government time to time, in case of non compliance with rules and regulations, user agreement and privacy policy, for access or usage of intermediaries computer resources, the Intermediary has the right to immediately terminate the access or usage rights of the users to the computer resources of Intermediaries and remove non-complaint information.',
      'You warrant that the information you provide to EduMindWell is accurate and complete. EduMindWell is entitled at all times to verify the information that you have provided and to refuse the Service or use of the website without providing reasons.',
      'In terms of Information Technology (Intermediaries guidelines) Rules 2011, you agree and undertake that you shall not host, display, upload, modify, publish, transmit, update or share any information that belongs to another person and to which you do not have any right; is unlawful, harmful, harassing, defamatory, obscene, invasive of privacy, hateful, racially or ethically objectionable, disparaging, encourages money laundering or gambling, harms minors, infringes intellectual property, involves junk mail or spam, violates law, misleads users, impersonates another person, contains malicious code, threatens the unity, integrity, defence, security or sovereignty of India, or is false, inaccurate or misleading.',
      'EduMindWell further reserves the right at its sole discretion to block or remove, in whole or in part, any content posted or transmitted by you and which EduMindWell believes is not in accordance with this EDUMINDWELL, or is otherwise unacceptable to EduMindWell.',
      'You agree to promptly notify EduMindWell in writing of any user content which breaches these User Terms. EduMindWell agrees to make good faith efforts to investigate such complaint and shall take such notice as EduMindWell in its sole discretion decides. However, EduMindWell does not warrant or represent that it will block or remove, in whole or in part, such user Content.',
    ],
  },
  {
    title: 'Consequences of Breach of Terms',
    paragraphs: [
      'Without limiting other remedies, EduMindWell may limit your activity, immediately remove your information or end your registration, warn other Users of your actions, temporarily or indefinitely suspend or terminate or block your membership, and/or refuse to provide you with access to the Website if you breach the EDUMINDWELL, Privacy Policy, or incorporated documents; if EduMindWell is unable to verify or authenticate any information provided by you; or if it is believed that your actions may cause legal liability for other Users or EduMindWell.',
      'User/s who have been suspended or blocked may not register or attempt to register with EduMindWell or use the Website in any manner whatsoever until permitted to do so by EduMindWell.',
      'If you breach the EDUMINDWELL or any other documents it incorporates by reference, EduMindWell reserves the right to forfeit the money paid by you to EduMindWell and to take strict legal action including but not limited to a referral to the appropriate police or the other authorities for initiating criminal or other proceedings against you.',
      'EduMindWell reserves its right to initiate civil and/or criminal proceedings against a user/s who furnishes invalid/false claim or misleading information to EduMindWell.',
      'Any person who knowingly and with an intent to injure, defraud or deceive EduMindWell files fraudulent information containing false, incomplete, or misleading information shall be guilty of a criminal offence and will be prosecuted to the fullest extent to the law.',
    ],
  },
  {
    title: 'Deficiency in Service',
    paragraphs: [
      'EduMindWell reserves the right to temporarily or indefinitely suspend or terminate your registration and refuse to provide you with access to all current and future use of the Website at its sole discretion which shall not be termed as deficiency in service in any manner as per law and the user/s hereby expressly waives its right to call in question in any manner, any such suspension/termination of services by the EduMindWell.',
      'EduMindWell reserves its right to suspend the operation of the website for updation/repair/technical fault or any other reason as the case may be for which it shall not be liable in any manner including for deficiency of service under the applicable laws.',
    ],
  },
  {
    title: 'Indemnity',
    paragraphs: [
      'You confirm that you shall be responsible for any damage that may be caused to EduMindWell for wrongful use of the website or its content by you including but not limited to Intellectual property Violations/Breach of terms and Conditions of EDUMINDWELL or in any manner as the case may be.',
      'By accepting User Terms and using the Website or Service, you agree that you shall defend, indemnify and hold EduMindWell, its affiliates, third-parties and their respective shareholders, officers, directors, agents, and employees, from any losses, liabilities, damages, costs and expenses, claim or demand, or actions including reasonable attorneys fees asserted against or incurred by EduMindWell, made by any third party arising out of or in connection with your violation or breach of any term of these User Terms or any applicable law or regulation, your violation of any rights of any third party, or your use or misuse of the Website or Services.',
    ],
  },
  {
    title: 'Liability and Limitation of Liability',
    paragraphs: [
      'The information, recommendations and/or services provided to you on or through the Website, the Service and the Website is for general information purposes only as bonafide guidance and does not constitute any commitment of performance of user in any manner.',
      'EduMindWell will reasonably keep the site and its contents correct and up to date but does not guarantee that the contents of the Website are free of errors, defects, malware and viruses or that the Website is correct, up to date and accurate.',
      'EduMindWell endeavors to render the utmost quality of the services rendered, however shall not be liable in any manner for any interruption in service for any reasons whatsoever.',
      'EduMindWell may permit advertisements of third parties on the website and shall not be responsible for the contents, assurances, services or anything relating to such third party advertisement in any manner whatsoever.',
      'In no event shall EduMindWell be liable for the amount more than that received by the EduMindWell from complainant user/s for any direct, indirect, incidental, special, consequential or exemplary damages including but not limited to damages for non admission/performance/loss of goodwill, use, data or other intangible losses arising out of or in connection with the website, its services or this agreement.',
      'EduMindWell assumes no liability whatsoever for any monetary or other damage suffered by you on account of delay, failure, interruption, corruption of data or other information transmitted in connection with use of the Website, or any interruption or errors in the operation of the Website.',
    ],
  },
  {
    title: 'Communication Policy',
    paragraphs: [
      'You are prohibited to engage in direct or indirect communication with Counselors/consultants of EduMindWell except for the purposes of the services availed by you.',
      'EduMindWell intermediates the communication between user/s and the Counselors which shall be limited for the purposes of service availed and the EduMindWell shall not be responsible for any communication between the user and the counselor beyond the scope of the services availed by the user/s in any manner whatsoever.',
      'Violations of policy may result in cancellation of your registration, limits on account privileges, account suspension, compensation for breach of duty, and other proceedings as the law may prescribe.',
    ],
  },
  {
    title: 'Notice',
    paragraphs: [
      'EduMindWell may give notice by means of a general notice on the Website, or by electronic mail to your e-mail address on record in EduMindWell account information, or by written communication sent by regular mail to your address on record in EduMindWell account information.',
      'You agree that all the agreements, notices, disclosures and other communications that we provide to you electronically shall be deemed adequate service of notice/electronic record and satisfy any legal requirement that such communication be in writing in terms of the present EDUMINDWELL.',
    ],
  },
  {
    title: 'Feedback',
    paragraphs: [
      'EduMindWell is always open to the suggestions of the user/s and shall endeavor to do all such suggestions that may enhance the utility to the user/s for the benefit of user/s as well as EduMindWell.',
      'However, EduMindWell is not bound by such suggestions in any manner whatsoever.',
    ],
  },
  {
    title: 'Dispute Resolution',
    paragraphs: [
      'The parties shall attempt that in the event of there being any dispute between them during your use of the Website or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of the User Agreement, or the documents they incorporate by reference or anything relating to the present EDUMINDWELL, the dispute is settled by mutual discussion. In the event of failure of discussion the dispute shall be referred to a sole Arbitrator, who shall be an independent and neutral third party appointed by EduMindWell. The place of arbitration shall be New Delhi, India. The Arbitration proceedings shall be in the English Language and shall be governed by Arbitration and Conciliation Act, 1996.',
    ],
  },
  {
    title: 'Jurisdiction',
    paragraphs: [
      'For any dispute arising out of the present agreement only the Courts at Mumbai would have Jurisdiction and you undertake not to raise challenge to the jurisdiction clause in any manner and accept the jurisdiction of the Court at Mumbai.',
    ],
  },
  {
    title: 'Severability',
    paragraphs: [
      'If any clause of this Agreement shall be deemed invalid, void or for any reason unenforceable, such clause shall be deemed severable and shall not affect the validity and enforceability of the remaining clauses of the Agreement.',
    ],
  },
  {
    title: 'General',
    paragraphs: [
      'You cannot assign or otherwise transfer this agreement or any rights granted here under to any third party. EduMindWell may transfer its rights and obligations, also known as assign, under this Agreement without your prior express consent, provided that EduMindWell assigns the Agreement on the same terms or terms that are no less advantageous to you.',
      'You undertake that you had every opportunity to take legal opinion on the present agreement and have understood the legal implications of every clause before agreeing to the same in totality and using the Website.',
    ],
  },
]
